### PR TITLE
Home Screen B

### PR DESCRIPTION
**Pull request by prmeherkaur**
Concept Validation: Home Screen B

### CODE REVIEW

**Comment by shishirarora3** [comment]
Figma
PR

**Comment by shishirarora3** [comment]
looks great, its responsive as well.
styling can be improved, underline of email tab, padding of list-items can be improved.
code not reviewed yet.
footer buttons are missing can be reused from other PRs.

**Comment by prmeherkaur** [comment]
Hi,
I will work on improving the styling for sure but I had added the footer
buttons using the provider, if it is not visible will make the necessary
changes so that the component is used directly

**Comment by shishirarora3** [comment]
Console Errors

**Pull request merged**
